export const BOOK_GENRES = [
  { id: 'roman', label: 'Roman' },
  { id: 'sf', label: 'Science-fiction' },
  { id: 'fantasy', label: 'Fantasy' },
  { id: 'thriller', label: 'Thriller' },
  { id: 'policier', label: 'Policier' },
  { id: 'romance', label: 'Romance' },
  { id: 'biographie', label: 'Biographie' },
  { id: 'histoire', label: 'Histoire' },
  { id: 'sciences', label: 'Sciences' },
  { id: 'dev-perso', label: 'Développement personnel' },
  { id: 'bd', label: 'BD' },
  { id: 'manga', label: 'Manga' },
  { id: 'jeunesse', label: 'Jeunesse' },
  { id: 'essai', label: 'Essai' },
  { id: 'philosophie', label: 'Philosophie' },
  { id: 'voyage', label: 'Voyage' },
  { id: 'art', label: 'Art' },
  { id: 'cuisine', label: 'Cuisine' },
] as const
